### PR TITLE
Map Screen UI # 2 

### PR DESCRIPTION
**Pull request by jarrencampos**
[TRELLO BOARD CARD](https://trello.com/c/cr6VAMpb/42-setup-ui-for-map-screen)
-------------------------
Location:
-MapScreen.storyboard
-MapScreenViewController.swift
-Main.storyboard
-------------------------
Details:
1) Fixed some UI elements and implemented a pop up view to display information to user.

### CODE REVIEW

**Comment by jarrencampos** [comment]
Added a temporary button on the login to bypass the search story board for testing purposes.

**Comment by FabiolaSaga** [comment]
Everything looks good, the only thing I noticed missing is the search button to take us back to the search page (binoculars icon). Really liked the pop up view with the blurred background!

**Comment by jarrencampos** [comment]
Forgot about that! Will add on my next PR

**Comment by jarrencampos** [comment]
[Setup UI for Map Screen](https://trello.com/c/cr6VAMpb/42-setup-ui-for-map-screen)

**Pull request merged**
